### ISSUE TITLE
A.02.TGR2.conformtoAtomSpecification.md - XML Schema

### ISSUE THREAD

**Issue by aquaglia** [inspire-eu-validation/download-service#46]
The ATS proposes to create an XML schema to validate an arbitrary atom feed.
That is certainly useful but it will not be enough since the ATOM specifications allows any order for the elements.
Before validating, the xml elements must be shuffled to match the order chosen in the XML schema.

**Comment by thijsbrentjens** [comment]
Good point. I made a Note in the ATS text for this.
