### ISSUE TITLE
A.11.IR221.TGR11.updatedelement,  A.18.TGR19.entryUpdated and A.23.IR221.TGR24.datasetFeedUpdated

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/download-service#60]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

Both tests check for validity of a date, but in a different way. 
# Proposed Change

Use the same way to check if a date is valid. NL prefers A.18.TGR19.entryUpdated (and A.23.IR221.TGR24.datasetFeedUpdated), so add to  A.11.IR221.TGR11.updatedelement to check on a valid date with 'year-from-dateTime(xs:dateTime(atom:updated))'

**Comment by cportele** [comment]
Proposed resolution:
- Implement proposed change.

**Comment by cportele** [comment]
Proposed resolution accepted by default. See [call on April 28](https://ies-svn.jrc.ec.europa.eu/projects/validation-and-conformity-testing/wiki/MIWP-5_meeting_10#Next-steps).
