### ISSUE TITLE
Reference to table in Service Metadata test

### ISSUE THREAD

**Issue by heidivanparys** [inspire-eu-validation/download-service#80]
The [Service Metadata](https://github.com/inspire-eu-validation/download-service/blob/3.1/wfs-pre-defined/service-metadata.md) test references Table 4 in the [Technical Guidelines](http://inspire.ec.europa.eu/documents/Network_Services/Technical_Guidance_Download_Services_v3.1.pdf). Isn't this a mistake in the TG? Shouldn't this be Table 19 instead? And the test description updated, with a note regarding this mistake?

![image](https://user-images.githubusercontent.com/11427611/35936680-d7e4be62-0c3b-11e8-9f67-308f5b5de377.png)

![image](https://user-images.githubusercontent.com/11427611/35936693-ddf7d168-0c3b-11e8-9c61-ef96a8d0f960.png)

**Comment by cportele** [comment]
Indeed. I tagged this for discussion in the MIG-T subgroup (although this looks like an obvious bug and likely just need to be fixed).

**Comment by michellutz** [comment]
I agree. This is a bug in the TG and should be fixed there and in the ATS.

Then we of course also need to check that the ETS implementation is using the correct table / mapping.

**Comment by michellutz** [comment]
[2017.4 meeting 2018-02-15] It was agreed that this should be fixed in the ATS (see #82) and it should be checked that the ETS implementation is using the correct table / mapping (action on me).

**Comment by michellutz** [comment]
From what I can tell,  ets-repository/service/ds-wfs-pre-defined-soapui-project.xml  seems to be using table 19. @jonherrmann could you please confirm?
The only change that would need to be made there is to also update the reference to table 19 in line 4924.

**Comment by jonherrmann** [comment]
The ETS is based on this ATC: http://inspire.ec.europa.eu/id/ats/download-service/3.1/wfs-pre-defined/service-metadata . Mainly the Contextual XPath references were used, taken from table 19.

So yes, I will create a PR in the ets-repository for changing the table reference.

**Comment by PeterParslow** [comment]
See also [https://github.com/inspire-eu-validation/download-service/issues/81](url) - the last row of Table 19 may be wrong.

**Comment by michellutz** [comment]
[2017.4 meeting 2018-03-16] The proposed change has been implemented in the relevant ATS and ETS.
